(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["index"],{

/***/ "./src/routes/index.svelte":
/*!*********************************!*\
  !*** ./src/routes/index.svelte ***!
  \*********************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var _components_News_svelte__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ../components/News.svelte */ "./src/components/News.svelte");
/* src/routes/index.svelte generated by Svelte v3.13.0 */



const file = "src/routes/index.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = "svelte-1eyy25k-style";
	style.textContent = "p.svelte-1eyy25k{text-align:center;margin:0 auto}p.svelte-1eyy25k{margin:1em auto}.logo.svelte-1eyy25k{display:flex;justify-content:center;align-items:center}@media(min-width: 480px){}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5kZXguc3ZlbHRlIiwic291cmNlcyI6WyJpbmRleC5zdmVsdGUiXSwic291cmNlc0NvbnRlbnQiOlsiPHNjcmlwdD5cbiAgaW1wb3J0IE5ld3MgZnJvbSBcIi4uL2NvbXBvbmVudHMvTmV3cy5zdmVsdGVcIjtcbjwvc2NyaXB0PlxuXG48c3R5bGU+XG4gIC8qIGgxLCAqL1xuICAvKiBmaWd1cmUsICovXG4gIHAge1xuICAgIHRleHQtYWxpZ246IGNlbnRlcjtcbiAgICBtYXJnaW46IDAgYXV0bztcbiAgfVxuXG4gIC8qIGgxIHtcbiAgICBmb250LXNpemU6IDIuOGVtO1xuICAgIHRleHQtdHJhbnNmb3JtOiB1cHBlcmNhc2U7XG4gICAgZm9udC13ZWlnaHQ6IDcwMDtcbiAgICBtYXJnaW46IDAgMCAwLjVlbSAwO1xuICB9ICovXG5cbiAgLyogICBmaWd1cmUge1xuICAgIG1hcmdpbjogMCAwIDFlbSAwO1xuICB9XG5cbiAgaW1nIHtcbiAgICB3aWR0aDogMTAwJTtcbiAgICBtYXgtd2lkdGg6IDQwMHB4O1xuICAgIG1hcmdpbjogMCAwIDFlbSAwO1xuICB9ICovXG5cbiAgcCB7XG4gICAgbWFyZ2luOiAxZW0gYXV0bztcbiAgfVxuICAubG9nbyB7XG4gICAgZGlzcGxheTogZmxleDtcbiAgICBqdXN0aWZ5LWNvbnRlbnQ6IGNlbnRlcjtcbiAgICBhbGlnbi1pdGVtczogY2VudGVyO1xuICB9XG4gIEBtZWRpYSAobWluLXdpZHRoOiA0ODBweCkge1xuICAgIC8qIGgxIHtcbiAgICAgIGZvbnQtc2l6ZTogNGVtO1xuICAgIH0gKi9cbiAgfVxuPC9zdHlsZT5cblxuPHN2ZWx0ZTpoZWFkPlxuICA8dGl0bGU+VGhlIEhlYWRsaW5lczwvdGl0bGU+XG48L3N2ZWx0ZTpoZWFkPlxuXG48ZGl2IGNsYXNzPVwibG9nb1wiPlxuICA8c3ZnXG4gICAgeG1sbnM9XCJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2Z1wiXG4gICAgd2lkdGg9XCIzMDZcIlxuICAgIGhlaWdodD1cIjYyXCJcbiAgICB2aWV3Qm94PVwiMCAwIDMwNiA2MlwiPlxuICAgIDx0ZXh0XG4gICAgICBpZD1cIlRoZV9MYXNnaWRpX1RpbWVzXCJcbiAgICAgIGRhdGEtbmFtZT1cIlRoZSBMYXNnaWRpIFRpbWVzXCJcbiAgICAgIHRyYW5zZm9ybT1cInRyYW5zbGF0ZSgwIDQ1KVwiXG4gICAgICBmaWxsPVwiIzAwMDAwXCJcbiAgICAgIGZvbnQtc2l6ZT1cIjQwXCJcbiAgICAgIGZvbnQtZmFtaWx5PVwiQ2hvbXNreVwiPlxuICAgICAgPHRzcGFuIHg9XCIwXCIgeT1cIjBcIj5UaGUgTGFzZ2lkaSBUaW1lczwvdHNwYW4+XG4gICAgPC90ZXh0PlxuICA8L3N2Zz5cbjwvZGl2PlxuXG48IS0tIDxoMT5MQVNHSURJIFRJTUVTPC9oMT4gLS0+XG5cbjwhLS0gPGZpZ3VyZT5cbiAgPGltZyBhbHQ9XCJCb3JhdFwiIHNyYz1cImdyZWF0LXN1Y2Nlc3MucG5nXCIgLz5cbiAgPGZpZ2NhcHRpb24+SElHSCBGSVZFITwvZmlnY2FwdGlvbj5cbjwvZmlndXJlPiAtLT5cblxuPHA+XG4gIDxzdHJvbmc+VG9wIFRyZW5kaW5nIEhlYWRsaW5lcyBjdXJyYXRlZCBmb3IgeW91PC9zdHJvbmc+XG5cbiAgPE5ld3MgLz5cbjwvcD5cbiJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFPRSxDQUFDLGVBQUMsQ0FBQyxBQUNELFVBQVUsQ0FBRSxNQUFNLENBQ2xCLE1BQU0sQ0FBRSxDQUFDLENBQUMsSUFBSSxBQUNoQixDQUFDLEFBbUJELENBQUMsZUFBQyxDQUFDLEFBQ0QsTUFBTSxDQUFFLEdBQUcsQ0FBQyxJQUFJLEFBQ2xCLENBQUMsQUFDRCxLQUFLLGVBQUMsQ0FBQyxBQUNMLE9BQU8sQ0FBRSxJQUFJLENBQ2IsZUFBZSxDQUFFLE1BQU0sQ0FDdkIsV0FBVyxDQUFFLE1BQU0sQUFDckIsQ0FBQyxBQUNELE1BQU0sQUFBQyxZQUFZLEtBQUssQ0FBQyxBQUFDLENBQUMsQUFJM0IsQ0FBQyJ9 */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(document.head, style);
}

function create_fragment(ctx) {
	let t0;
	let div;
	let svg;
	let text_1;
	let tspan;
	let t1;
	let t2;
	let p;
	let strong;
	let t3;
	let t4;
	let current;
	const news = new _components_News_svelte__WEBPACK_IMPORTED_MODULE_1__["default"]({ $$inline: true });

	const block = {
		c: function create() {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			svg = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("svg");
			text_1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("text");
			tspan = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("tspan");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("The Lasgidi Times");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			strong = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("strong");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Top Trending Headlines currated for you");
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(news.$$.fragment);
			this.h();
		},
		l: function claim(nodes) {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(nodes);
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true });
			var div_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div);

			svg = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(
				div_nodes,
				"svg",
				{
					xmlns: true,
					width: true,
					height: true,
					viewBox: true
				},
				1
			);

			var svg_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(svg);

			text_1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(
				svg_nodes,
				"text",
				{
					id: true,
					"data-name": true,
					transform: true,
					fill: true,
					"font-size": true,
					"font-family": true
				},
				1
			);

			var text_1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(text_1);
			tspan = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(text_1_nodes, "tspan", { x: true, y: true }, 1);
			var tspan_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(tspan);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(tspan_nodes, "The Lasgidi Times");
			tspan_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			text_1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			svg_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(nodes);
			p = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "P", { class: true });
			var p_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p);
			strong = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(p_nodes, "STRONG", {});
			var strong_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(strong);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(strong_nodes, "Top Trending Headlines currated for you");
			strong_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(p_nodes);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(news.$$.fragment, p_nodes);
			p_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			document.title = "The Headlines";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(tspan, "x", "0");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(tspan, "y", "0");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(tspan, file, 61, 6, 974);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text_1, "id", "The_Lasgidi_Times");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text_1, "data-name", "The Lasgidi Times");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text_1, "transform", "translate(0 45)");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text_1, "fill", "#00000");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text_1, "font-size", "40");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text_1, "font-family", "Chomsky");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(text_1, file, 54, 4, 793);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(svg, "xmlns", "http://www.w3.org/2000/svg");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(svg, "width", "306");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(svg, "height", "62");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(svg, "viewBox", "0 0 306 62");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(svg, file, 49, 2, 687);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div, "class", "logo svelte-1eyy25k");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div, file, 48, 0, 666);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(strong, file, 74, 2, 1200);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(p, "class", "svelte-1eyy25k");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p, file, 73, 0, 1194);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, div, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div, svg);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(svg, text_1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(text_1, tspan);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(tspan, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t2, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, p, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p, strong);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(strong, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p, t4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(news, p, null);
			current = true;
		},
		p: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(news.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(news.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t0);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(div);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t2);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(p);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(news);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

class Routes extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-1eyy25k-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, null, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], {});

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "Routes",
			options,
			id: create_fragment.name
		});
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Routes);

/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vd2VicGFjazovLy93ZWJwYWNrOi8vL3dlYnBhY2s6Ly8vd2VicGFjazovLy93ZWJwYWNrOi8vL3dlYnBhY2s6Ly8vd2VicGFjazovLy93ZWJwYWNrOi8vL3dlYnBhY2s6Ly8vd2VicGFjazovLy93ZWJwYWNrOi8vL3dlYnBhY2s6Ly8vd2VicGFjazovLy93ZWJwYWNrOi8vL3dlYnBhY2s6Ly8vd2VicGFjazovLy93ZWJwYWNrOi8vL3dlYnBhY2s6Ly8vd2VicGFjazovLy93ZWJwYWNrOi8vL3dlYnBhY2s6Ly8vd2VicGFjazovLy93ZWJwYWNrOi8vL3dlYnBhY2s6Ly8vd2VicGFjazovLy93ZWJwYWNrOi8vL3dlYnBhY2s6Ly8vd2VicGFjazovLy93ZWJwYWNrOi8vL3dlYnBhY2s6Ly8vd2VicGFjazovLy93ZWJwYWNrOi8vL3dlYnBhY2s6Ly8vd2VicGFjazovLy93ZWJwYWNrOi8vL3dlYnBhY2s6Ly8vd2VicGFjazovLy93ZWJwYWNrOi8vL3dlYnBhY2s6Ly8vd2VicGFjazovLy93ZWJwYWNrOi8vLy4vc3JjL3JvdXRlcy9pbmRleC5zdmVsdGUiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Ozs7Ozs7OztBQUMrQyIsImZpbGUiOiI4ZjRlNDQ5YjY1Nzk2OWNhYTQ0Ny9pbmRleC5pbmRleC5qcyIsInNvdXJjZXNDb250ZW50IjpbIjxzY3JpcHQ+XG4gIGltcG9ydCBOZXdzIGZyb20gXCIuLi9jb21wb25lbnRzL05ld3Muc3ZlbHRlXCI7XG48L3NjcmlwdD5cblxuPHN0eWxlPlxuICAvKiBoMSwgKi9cbiAgLyogZmlndXJlLCAqL1xuICBwIHtcbiAgICB0ZXh0LWFsaWduOiBjZW50ZXI7XG4gICAgbWFyZ2luOiAwIGF1dG87XG4gIH1cblxuICAvKiBoMSB7XG4gICAgZm9udC1zaXplOiAyLjhlbTtcbiAgICB0ZXh0LXRyYW5zZm9ybTogdXBwZXJjYXNlO1xuICAgIGZvbnQtd2VpZ2h0OiA3MDA7XG4gICAgbWFyZ2luOiAwIDAgMC41ZW0gMDtcbiAgfSAqL1xuXG4gIC8qICAgZmlndXJlIHtcbiAgICBtYXJnaW46IDAgMCAxZW0gMDtcbiAgfVxuXG4gIGltZyB7XG4gICAgd2lkdGg6IDEwMCU7XG4gICAgbWF4LXdpZHRoOiA0MDBweDtcbiAgICBtYXJnaW46IDAgMCAxZW0gMDtcbiAgfSAqL1xuXG4gIHAge1xuICAgIG1hcmdpbjogMWVtIGF1dG87XG4gIH1cbiAgLmxvZ28ge1xuICAgIGRpc3BsYXk6IGZsZXg7XG4gICAganVzdGlmeS1jb250ZW50OiBjZW50ZXI7XG4gICAgYWxpZ24taXRlbXM6IGNlbnRlcjtcbiAgfVxuICBAbWVkaWEgKG1pbi13aWR0aDogNDgwcHgpIHtcbiAgICAvKiBoMSB7XG4gICAgICBmb250LXNpemU6IDRlbTtcbiAgICB9ICovXG4gIH1cbjwvc3R5bGU+XG5cbjxzdmVsdGU6aGVhZD5cbiAgPHRpdGxlPlRoZSBIZWFkbGluZXM8L3RpdGxlPlxuPC9zdmVsdGU6aGVhZD5cblxuPGRpdiBjbGFzcz1cImxvZ29cIj5cbiAgPHN2Z1xuICAgIHhtbG5zPVwiaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmdcIlxuICAgIHdpZHRoPVwiMzA2XCJcbiAgICBoZWlnaHQ9XCI2MlwiXG4gICAgdmlld0JveD1cIjAgMCAzMDYgNjJcIj5cbiAgICA8dGV4dFxuICAgICAgaWQ9XCJUaGVfTGFzZ2lkaV9UaW1lc1wiXG4gICAgICBkYXRhLW5hbWU9XCJUaGUgTGFzZ2lkaSBUaW1lc1wiXG4gICAgICB0cmFuc2Zvcm09XCJ0cmFuc2xhdGUoMCA0NSlcIlxuICAgICAgZmlsbD1cIiMwMDAwMFwiXG4gICAgICBmb250LXNpemU9XCI0MFwiXG4gICAgICBmb250LWZhbWlseT1cIkNob21za3lcIj5cbiAgICAgIDx0c3BhbiB4PVwiMFwiIHk9XCIwXCI+VGhlIExhc2dpZGkgVGltZXM8L3RzcGFuPlxuICAgIDwvdGV4dD5cbiAgPC9zdmc+XG48L2Rpdj5cblxuPCEtLSA8aDE+TEFTR0lESSBUSU1FUzwvaDE+IC0tPlxuXG48IS0tIDxmaWd1cmU+XG4gIDxpbWcgYWx0PVwiQm9yYXRcIiBzcmM9XCJncmVhdC1zdWNjZXNzLnBuZ1wiIC8+XG4gIDxmaWdjYXB0aW9uPkhJR0ggRklWRSE8L2ZpZ2NhcHRpb24+XG48L2ZpZ3VyZT4gLS0+XG5cbjxwPlxuICA8c3Ryb25nPlRvcCBUcmVuZGluZyBIZWFkbGluZXMgY3VycmF0ZWQgZm9yIHlvdTwvc3Ryb25nPlxuXG4gIDxOZXdzIC8+XG48L3A+XG4iXSwic291cmNlUm9vdCI6IiJ9