(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["index"],{

/***/ "./src/routes/index.svelte":
/*!*********************************!*\
  !*** ./src/routes/index.svelte ***!
  \*********************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var _components_News_svelte__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ../components/News.svelte */ "./src/components/News.svelte");
/* src/routes/index.svelte generated by Svelte v3.13.0 */



const file = "src/routes/index.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = "svelte-1eyy25k-style";
	style.textContent = "p.svelte-1eyy25k{text-align:center;margin:0 auto}p.svelte-1eyy25k{margin:1em auto}.logo.svelte-1eyy25k{display:flex;justify-content:center;align-items:center}@media(min-width: 480px){}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5kZXguc3ZlbHRlIiwic291cmNlcyI6WyJpbmRleC5zdmVsdGUiXSwic291cmNlc0NvbnRlbnQiOlsiPHNjcmlwdD5cbiAgaW1wb3J0IE5ld3MgZnJvbSBcIi4uL2NvbXBvbmVudHMvTmV3cy5zdmVsdGVcIjtcbjwvc2NyaXB0PlxuXG48c3R5bGU+XG4gIC8qIGgxLCAqL1xuICAvKiBmaWd1cmUsICovXG4gIHAge1xuICAgIHRleHQtYWxpZ246IGNlbnRlcjtcbiAgICBtYXJnaW46IDAgYXV0bztcbiAgfVxuXG4gIC8qIGgxIHtcbiAgICBmb250LXNpemU6IDIuOGVtO1xuICAgIHRleHQtdHJhbnNmb3JtOiB1cHBlcmNhc2U7XG4gICAgZm9udC13ZWlnaHQ6IDcwMDtcbiAgICBtYXJnaW46IDAgMCAwLjVlbSAwO1xuICB9ICovXG5cbiAgLyogICBmaWd1cmUge1xuICAgIG1hcmdpbjogMCAwIDFlbSAwO1xuICB9XG5cbiAgaW1nIHtcbiAgICB3aWR0aDogMTAwJTtcbiAgICBtYXgtd2lkdGg6IDQwMHB4O1xuICAgIG1hcmdpbjogMCAwIDFlbSAwO1xuICB9ICovXG5cbiAgcCB7XG4gICAgbWFyZ2luOiAxZW0gYXV0bztcbiAgfVxuICAubG9nbyB7XG4gICAgZGlzcGxheTogZmxleDtcbiAgICBqdXN0aWZ5LWNvbnRlbnQ6IGNlbnRlcjtcbiAgICBhbGlnbi1pdGVtczogY2VudGVyO1xuICB9XG4gIEBtZWRpYSAobWluLXdpZHRoOiA0ODBweCkge1xuICAgIC8qIGgxIHtcbiAgICAgIGZvbnQtc2l6ZTogNGVtO1xuICAgIH0gKi9cbiAgfVxuPC9zdHlsZT5cblxuPHN2ZWx0ZTpoZWFkPlxuICA8dGl0bGU+VGhlIEhlYWRsaW5lczwvdGl0bGU+XG48L3N2ZWx0ZTpoZWFkPlxuXG48ZGl2IGNsYXNzPVwibG9nb1wiPlxuICA8c3ZnXG4gICAgeG1sbnM9XCJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2Z1wiXG4gICAgd2lkdGg9XCIzMDZcIlxuICAgIGhlaWdodD1cIjYyXCJcbiAgICB2aWV3Qm94PVwiMCAwIDMwNiA2MlwiPlxuICAgIDx0ZXh0XG4gICAgICBpZD1cIlRoZV9MYXNnaWRpX1RpbWVzXCJcbiAgICAgIGRhdGEtbmFtZT1cIlRoZSBMYXNnaWRpIFRpbWVzXCJcbiAgICAgIHRyYW5zZm9ybT1cInRyYW5zbGF0ZSgwIDQ1KVwiXG4gICAgICBmaWxsPVwiIzAwMDAwXCJcbiAgICAgIGZvbnQtc2l6ZT1cIjQwXCJcbiAgICAgIGZvbnQtZmFtaWx5PVwiQ2hvbXNreVwiPlxuICAgICAgPHRzcGFuIHg9XCIwXCIgeT1cIjBcIj5UaGUgTGFzZ2lkaSBUaW1lczwvdHNwYW4+XG4gICAgPC90ZXh0PlxuICA8L3N2Zz5cbjwvZGl2PlxuXG48IS0tIDxoMT5MQVNHSURJIFRJTUVTPC9oMT4gLS0+XG5cbjwhLS0gPGZpZ3VyZT5cbiAgPGltZyBhbHQ9XCJCb3JhdFwiIHNyYz1cImdyZWF0LXN1Y2Nlc3MucG5nXCIgLz5cbiAgPGZpZ2NhcHRpb24+SElHSCBGSVZFITwvZmlnY2FwdGlvbj5cbjwvZmlndXJlPiAtLT5cblxuPHA+XG4gIDxzdHJvbmc+VG9wIFRyZW5kaW5nIEhlYWRsaW5lcyBjdXJyYXRlZCBmb3IgeW91PC9zdHJvbmc+XG5cbiAgPE5ld3MgLz5cbjwvcD5cbiJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFPRSxDQUFDLGVBQUMsQ0FBQyxBQUNELFVBQVUsQ0FBRSxNQUFNLENBQ2xCLE1BQU0sQ0FBRSxDQUFDLENBQUMsSUFBSSxBQUNoQixDQUFDLEFBbUJELENBQUMsZUFBQyxDQUFDLEFBQ0QsTUFBTSxDQUFFLEdBQUcsQ0FBQyxJQUFJLEFBQ2xCLENBQUMsQUFDRCxLQUFLLGVBQUMsQ0FBQyxBQUNMLE9BQU8sQ0FBRSxJQUFJLENBQ2IsZUFBZSxDQUFFLE1BQU0sQ0FDdkIsV0FBVyxDQUFFLE1BQU0sQUFDckIsQ0FBQyxBQUNELE1BQU0sQUFBQyxZQUFZLEtBQUssQ0FBQyxBQUFDLENBQUMsQUFJM0IsQ0FBQyJ9 */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(document.head, style);
}

function create_fragment(ctx) {
	let t0;
	let div;
	let svg;
	let text_1;
	let tspan;
	let t1;
	let t2;
	let p;
	let strong;
	let t3;
	let t4;
	let current;
	const news = new _components_News_svelte__WEBPACK_IMPORTED_MODULE_1__["default"]({ $$inline: true });

	const block = {
		c: function create() {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			svg = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("svg");
			text_1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("text");
			tspan = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("tspan");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("The Lasgidi Times");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			strong = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("strong");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Top Trending Headlines currated for you");
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(news.$$.fragment);
			this.h();
		},
		l: function claim(nodes) {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(nodes);
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true });
			var div_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div);

			svg = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(
				div_nodes,
				"svg",
				{
					xmlns: true,
					width: true,
					height: true,
					viewBox: true
				},
				1
			);

			var svg_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(svg);

			text_1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(
				svg_nodes,
				"text",
				{
					id: true,
					"data-name": true,
					transform: true,
					fill: true,
					"font-size": true,
					"font-family": true
				},
				1
			);

			var text_1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(text_1);
			tspan = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(text_1_nodes, "tspan", { x: true, y: true }, 1);
			var tspan_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(tspan);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(tspan_nodes, "The Lasgidi Times");
			tspan_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			text_1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			svg_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(nodes);
			p = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "P", { class: true });
			var p_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p);
			strong = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(p_nodes, "STRONG", {});
			var strong_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(strong);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(strong_nodes, "Top Trending Headlines currated for you");
			strong_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(p_nodes);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(news.$$.fragment, p_nodes);
			p_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			document.title = "The Headlines";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(tspan, "x", "0");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(tspan, "y", "0");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(tspan, file, 61, 6, 974);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text_1, "id", "The_Lasgidi_Times");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text_1, "data-name", "The Lasgidi Times");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text_1, "transform", "translate(0 45)");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text_1, "fill", "#00000");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text_1, "font-size", "40");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text_1, "font-family", "Chomsky");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(text_1, file, 54, 4, 793);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(svg, "xmlns", "http://www.w3.org/2000/svg");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(svg, "width", "306");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(svg, "height", "62");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(svg, "viewBox", "0 0 306 62");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(svg, file, 49, 2, 687);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div, "class", "logo svelte-1eyy25k");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div, file, 48, 0, 666);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(strong, file, 74, 2, 1200);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(p, "class", "svelte-1eyy25k");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p, file, 73, 0, 1194);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, div, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div, svg);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(svg, text_1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(text_1, tspan);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(tspan, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t2, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, p, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p, strong);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(strong, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p, t4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(news, p, null);
			current = true;
		},
		p: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(news.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(news.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t0);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(div);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t2);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(p);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(news);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

class Routes extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-1eyy25k-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, null, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], {});

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "Routes",
			options,
			id: create_fragment.name
		});
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Routes);

/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vd2VicGFjazovLy8uL3NyYy9yb3V0ZXMvaW5kZXguc3ZlbHRlIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7Ozs7Ozs7Ozs7QUFDK0MiLCJmaWxlIjoiZDRmMGU4NGY5NThhZjFhN2VhMWIvaW5kZXguaW5kZXguanMiLCJzb3VyY2VzQ29udGVudCI6WyI8c2NyaXB0PlxuICBpbXBvcnQgTmV3cyBmcm9tIFwiLi4vY29tcG9uZW50cy9OZXdzLnN2ZWx0ZVwiO1xuPC9zY3JpcHQ+XG5cbjxzdHlsZT5cbiAgLyogaDEsICovXG4gIC8qIGZpZ3VyZSwgKi9cbiAgcCB7XG4gICAgdGV4dC1hbGlnbjogY2VudGVyO1xuICAgIG1hcmdpbjogMCBhdXRvO1xuICB9XG5cbiAgLyogaDEge1xuICAgIGZvbnQtc2l6ZTogMi44ZW07XG4gICAgdGV4dC10cmFuc2Zvcm06IHVwcGVyY2FzZTtcbiAgICBmb250LXdlaWdodDogNzAwO1xuICAgIG1hcmdpbjogMCAwIDAuNWVtIDA7XG4gIH0gKi9cblxuICAvKiAgIGZpZ3VyZSB7XG4gICAgbWFyZ2luOiAwIDAgMWVtIDA7XG4gIH1cblxuICBpbWcge1xuICAgIHdpZHRoOiAxMDAlO1xuICAgIG1heC13aWR0aDogNDAwcHg7XG4gICAgbWFyZ2luOiAwIDAgMWVtIDA7XG4gIH0gKi9cblxuICBwIHtcbiAgICBtYXJnaW46IDFlbSBhdXRvO1xuICB9XG4gIC5sb2dvIHtcbiAgICBkaXNwbGF5OiBmbGV4O1xuICAgIGp1c3RpZnktY29udGVudDogY2VudGVyO1xuICAgIGFsaWduLWl0ZW1zOiBjZW50ZXI7XG4gIH1cbiAgQG1lZGlhIChtaW4td2lkdGg6IDQ4MHB4KSB7XG4gICAgLyogaDEge1xuICAgICAgZm9udC1zaXplOiA0ZW07XG4gICAgfSAqL1xuICB9XG48L3N0eWxlPlxuXG48c3ZlbHRlOmhlYWQ+XG4gIDx0aXRsZT5UaGUgSGVhZGxpbmVzPC90aXRsZT5cbjwvc3ZlbHRlOmhlYWQ+XG5cbjxkaXYgY2xhc3M9XCJsb2dvXCI+XG4gIDxzdmdcbiAgICB4bWxucz1cImh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnXCJcbiAgICB3aWR0aD1cIjMwNlwiXG4gICAgaGVpZ2h0PVwiNjJcIlxuICAgIHZpZXdCb3g9XCIwIDAgMzA2IDYyXCI+XG4gICAgPHRleHRcbiAgICAgIGlkPVwiVGhlX0xhc2dpZGlfVGltZXNcIlxuICAgICAgZGF0YS1uYW1lPVwiVGhlIExhc2dpZGkgVGltZXNcIlxuICAgICAgdHJhbnNmb3JtPVwidHJhbnNsYXRlKDAgNDUpXCJcbiAgICAgIGZpbGw9XCIjMDAwMDBcIlxuICAgICAgZm9udC1zaXplPVwiNDBcIlxuICAgICAgZm9udC1mYW1pbHk9XCJDaG9tc2t5XCI+XG4gICAgICA8dHNwYW4geD1cIjBcIiB5PVwiMFwiPlRoZSBMYXNnaWRpIFRpbWVzPC90c3Bhbj5cbiAgICA8L3RleHQ+XG4gIDwvc3ZnPlxuPC9kaXY+XG5cbjwhLS0gPGgxPkxBU0dJREkgVElNRVM8L2gxPiAtLT5cblxuPCEtLSA8ZmlndXJlPlxuICA8aW1nIGFsdD1cIkJvcmF0XCIgc3JjPVwiZ3JlYXQtc3VjY2Vzcy5wbmdcIiAvPlxuICA8ZmlnY2FwdGlvbj5ISUdIIEZJVkUhPC9maWdjYXB0aW9uPlxuPC9maWd1cmU+IC0tPlxuXG48cD5cbiAgPHN0cm9uZz5Ub3AgVHJlbmRpbmcgSGVhZGxpbmVzIGN1cnJhdGVkIGZvciB5b3U8L3N0cm9uZz5cblxuICA8TmV3cyAvPlxuPC9wPlxuIl0sInNvdXJjZVJvb3QiOiIifQ==